# CI Name
name: 'Deployment'

# Only running when
on:
    push:
        branches:
            - main

jobs:
    deploy:
        # Running on latest version of Ubuntu
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Deployment to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                  heroku_email: ${{ secrets.HEROKU_API_EMAIL }}
